### ISSUE TITLE
[FEATURE REQUEST]: seel to drugs

### ISSUE THREAD

**Issue by AmIsraelHai** [it-scripts/it-drugs#12]
### Is your feature request related to a problem? Please describe.

Good evening possible to make a modification please, on the fact of selling in areas I would like to be able to sell everywhere to all NPCs not only in a defined area

### Describe the solution you'd like

Good evening possible to make a modification please, on the fact of selling in areas I would like to be able to sell everywhere to all NPCs not only in a defined area

### Describe alternatives you've considered

Good evening possible to make a modification please, on the fact of selling in areas I would like to be able to sell everywhere to all NPCs not only in a defined area

### Additional context

Good evening possible to make a modification please, on the fact of selling in areas I would like to be able to sell everywhere to all NPCs not only in a defined area

**Comment by AllRoundJonU** [comment]
@AmIsraelHai now possible with version:

https://github.com/it-scripts/it-drugs/releases/tag/v1.3.0beta1
