### ISSUE TITLE
[BUG REPORT]: client/cl_notarget.lua

### ISSUE THREAD

**Issue by JB8099** [it-scripts/it-drugs#14]
### Version of the Script

1.2.4

### Describe the bug

could not find client_script `client/cl_notarget.lua` (defined in fxmanifest.lua:19)

### To Reproduce

```bash
could not find client_script `client/cl_notarget.lua` (defined in fxmanifest.lua:19)
```

**Comment by AllRoundJonU** [comment]
Hey this "bug" comes from the fact that I am working on a no_target version of the script but it is not yet ready for version 1.2.4, so the file is missing but is in the fxmanifest. If you don't want this message to appear you can simply delete the corresponding line from the fxmanifest file.
