### ISSUE TITLE
SCRIPT ERROR @it—drugsc1ientc1_processing.Lua197

### ISSUE THREAD

**Issue by Densen013** [it-scripts/it-drugs#15]
### Version of the Script

1.2.4

### Describe the bug

SCRIPT ERROR @it—drugsc1ientc1_processing.1ua197 attempt to index a nil value (field i animationi)
 handler (@it—drugsc1ientc1_processing.1ua197)

### To Reproduce

```bash
SCRIPT ERROR @it—drugsc1ientc1_processing.1ua197 attempt to index a nil value (field i animationi)
 handler (@it—drugsc1ientc1_processing.1ua197)
```

### Relevant log output

```shell
SCRIPT ERROR @it—drugsc1ientc1_processing.1ua197 attempt to index a nil value (field i animationi)
 handler (@it—drugsc1ientc1_processing.1ua197)
```

**Comment by AllRoundJonU** [comment]
Hey please join https://discord.it-scripts.com and I will help you
