### ISSUE TITLE
[BUG REPORT]: 

### ISSUE THREAD

**Issue by Bozzy171** [it-scripts/it-drugs#16]
### Version of the Script

v1.2.4

### Describe the bug

-- Target system ('qb-target', 'ox_target' or false to disable)
Config.Target = false

### To Reproduce

```bash
When set to false it needs to allow the target setups to work off distance with peds and press Config.Inetactkey = 'E' to allow people to still use this script. without target you cannot do a thing. Make this a redundant resource
```

**Comment by AllRoundJonU** [comment]
Hey, this is a feature that is coming in a new version of the script. Currently it is not possible to use the script without a target script. Sorry for the confusion.

**Comment by Bozzy171** [comment]
No dramas!
