### ISSUE TITLE
[BUG REPORT]: Console error.

### ISSUE THREAD

**Issue by LYRYCAL** [it-scripts/it-drugs#18]
### Version of the Script

1.2.4

### Describe the bug

Everytime try to give fertilizer & water to the plants.
Im using ps-inventory.
![Screenshot_9](https://github.com/user-attachments/assets/5dfb9050-abfd-48b3-8153-6b4b9efce5fa)

### To Reproduce

```bash
1. Planting weed.
2. Try to give fertilizer & water to the plants.
3. Error show up on the console.
```

**Comment by TheRockZz** [comment]
hey, same bug over here. after some testing we found out that the script is pushing the error because you dont have all 4 drug items if you have all 4 in your inventory you dont get any error.

**Comment by AllRoundJonU** [comment]
Hey @TheRockZz thanks for this Information I will check this and it will be fixed in the next version

**Comment by AllRoundJonU** [comment]
@TheRockZz Does the bug occur when the menu with the items for watering or fertilizing opens or only when you select an item?

**Comment by TheRockZz** [comment]
@AllRoundJonU Sorry for my late reply, the bug occurs when the menu for watering and fertilizing is opened. In debug mode, only the debug message 
“[ script:it-drugs] [it-drugs] The item liquid_fertilizer does not exist in the inventory.” is displayed in the server console.

Without debug mode the error.

The Script error only occurs if a player does not have all 4 possible items in their inventory for fertilizing and watering.

**Comment by AllRoundJonU** [comment]
Okay @TheRockZz for the details. I reworte the complete bridge for version 1.3.0 I hope this will fix this error

**Comment by AllRoundJonU** [comment]
@TheRockZz @LYRYCAL check if https://github.com/it-scripts/it-drugs/releases/tag/v1.3.0beta1 fixes this error for you
