### ISSUE TITLE
[BUG REPORT]: ItemData Error

### ISSUE THREAD

**Issue by andrewquincey** [it-scripts/it-drugs#19]
### Version of the Script

1.2.4

### Describe the bug

SCRIPT ERROR: @it-drugs/bridge/items/server.lua:25: attempt to index a nil value (local 'itemData')

### To Reproduce

```bash
Whenever someone targets a plant this error appears and plants are not visible for most people on the server.
```

**Comment by AllRoundJonU** [comment]
Hey @andrewquincey the first error will hopefully be fixed with version 1.3.0. For the secon one it it possible for you to join my discord server and create a ticket then it will be easier to communicate.

Discord: https://discord.it-scripts.com
