### ISSUE TITLE
[FEATURE REQUEST]: Qbox Compatibility

### ISSUE THREAD

**Issue by NotOliverYoung** [it-scripts/it-drugs#21]
### Is your feature request related to a problem? Please describe.

It would be great if you could add Qbox Compatibility as many users now days have started using Qbox due to the QB-Core drama. Qbox usually works with QB-core scripts, but for some reason this script doesn't work on it.

### Describe the solution you'd like

Add a bridge for Qbox

### Describe alternatives you've considered

N/A

**Comment by AllRoundJonU** [comment]
I will check this, should be possible to ad qbox support but I need some time

**Comment by AllRoundJonU** [comment]
@NotOliverYoung check https://github.com/it-scripts/it-drugs/releases/tag/v1.3.0beta5

**Comment by NotOliverYoung** [comment]
Thanks very much!
