### ISSUE TITLE
[BUG REPORT]: 

### ISSUE THREAD

**Issue by D3lta-Byte** [it-scripts/it-drugs#28]
### Version of the Script

latest

### Describe the bug

Progressbar

### To Reproduce

```bash
How can i change it so script uses my own progressbar ?
```

**Comment by AllRoundJonU** [comment]
Check this: https://github.com/it-scripts/it-drugs/blob/v1.3.0beta/shared/functions.lua

With the beta ist should be possible

**Comment by SpicyGun** [comment]
![error](https://github.com/user-attachments/assets/7b7b75b3-65ec-4f4f-ab3e-6017d5741b1f)
i have this error when planting (beta version)
