### ISSUE TITLE
[BUG REPORT]: 

### ISSUE THREAD

**Issue by bakerzone** [it-scripts/it-drugs#7]
### Version of the Script

1.22

### Describe the bug

Unable to sell any drugs after adding other drugs to the drugs/items list.
Using QBCORE with ox_inventory
The check for checking if the player has an item doesn't pick up the items,  even if you have the original items on you, these are not picked up, the Notificat:
	if playerItems == 0 then
		ShowNotification(nil, _U('NOTIFICATION__NO__DRUGS'), 'error')
		SetPedAsNoLongerNeeded(entity)
		return
	end
	
	Is called each and every time.

### To Reproduce

```bash
Add these to the config, in both or one location:
        drugs = {
            { item = 'cocaine', price = math.random(80, 120)},
            { item = 'joint', price = math.random(10, 30)},
            { item = 'weed_white-widow', price = math.random(20, 75)},
            { item = 'marijuana', price = math.random(20, 100)},
            { item = 'methbaggy', price = math.random(110, 150)},
            { item = 'weed_og-kush', price = math.random(50, 100)},
            { item = 'weed_skunk', price = math.random(50, 100)},
            { item = 'weed_amnesia', price = math.random(50, 100)},
            { item = 'weed_purple-haze', price = math.random(50, 100)},
            { item = 'weed_ak47', price = math.random(50, 100)},
            { item = 'crack_baggy', price = math.random(180, 340)},
            { item = 'cokebaggy', price = math.random(200, 400)},
            { item = 'heroin', price = math.random(250, 500)},
            { item = 'methbaggy', price = math.random(200, 300)},
            { item = 'meth', price = math.random(300, 350)},
            { item = 'puremethbaggy', price = math.random(300, 350)},
            { item = 'coke_brick', price = math.random(3000, 5000)},
            { item = 'shroombag', price = math.random(150, 250)},
            { item = 'weed_lemonhaze', price = math.random(20, 75)}
        }
    },

Doesn't matter if you restart the whole server or the single script ... there is no means to walk up to a ped and sell.
```

### Relevant log output

```shell
No errors generated, the trigger for having nothing on you to sell is called.
```

**Comment by AllRoundJonU** [comment]
I will have a look at this ✅

**Comment by AllRoundJonU** [comment]
Hey @bakerzone I am unable to recreate your error with the newest Version of the Script. Do you still have the error with the new version?

**Comment by bakerzone** [comment]
Strange ...  as it never works for me, well, tell a lie, if I add more drugs that you can sell, restart the script, you can sell once, then if you give yourself more of the same drug, or any other, each and every time it will say you have nothing available to sell.

No worries, if you cannot replicate, then it is what it is ... I'll use another drug selling script .. but thanks for checking .. shame as I liked this one.

**Comment by AllRoundJonU** [comment]
Ahh now I understand the problem, this is not a bug :sweat: Every time you want to sell a combination of random drugs created as a request and if the drug the customer wants is not in the inventory then this message comes up.

**Comment by bakerzone** [comment]
Hi Jon,

I get what is happening, now you've said that .. if you have multiple drugs available to be sold in the zones, and only 1 or 2 are in the inventory, it is possible for the ped to want to purchase other drugs that are included that could be sold in that zone.
S it is best to have multiple zones where you can sell different types of drugs .. I understand.
