### ISSUE TITLE
[FEATURE REQUEST]: need to check the distance between one plant and another

### ISSUE THREAD

**Issue by xamixami471** [it-scripts/it-drugs#8]
### Is your feature request related to a problem? Please describe.

you may need to check the distance between one plant and another, 
![double](https://github.com/it-scripts/it-drugs/assets/142724123/60113e93-8546-49d8-926f-2174829eda3d)

### Describe the solution you'd like

you can give a distance of 1.5 to 2 meters, players can only plant at a distance of <= 1.5 to 2 meters

### Describe alternatives you've considered

for _, existingCoords in ipairs(plantCoordinates) do
        local distance = #(coords - existingCoords)
        if distance < 2.0 then
            ShowNotification(nil, _U('NOTIFICATION__TOO_CLOSE'), "error")
            DeleteObject(plant)
            return
        end
    end

**Comment by AllRoundJonU** [comment]
Will be included in update v1.2.3 coming this week @xamixami471

**Comment by AllRoundJonU** [comment]
See comit: https://github.com/it-scripts/it-drugs/commit/b5ad9377973719b1eeebce5df1c344eda7724a57
